name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Run tests
        run: |
          mkdir tmp && chmod 0777 tmp
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run test
          sed -i "s%/app/%./%g" ./tmp/coverage-report.clover
          sed -i "s%/app/%./%g" ./tmp/test-report.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
